spring.application.name=notification-service

server.port=8095
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=notification-group

management.endpoints.web.exposure.include=*
management.info.env.enabled=true


eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.tracing.sampling.probability=1.0

management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
