apiVersion: apps/v1
kind: Deployment

metadata:
  name: service-registry

spec:
  replicas: 1

  selector:
    matchLabels:
      app: service-registry

  template:
    metadata:
      labels:
        app: service-registry

    spec:
      containers:
      - name: service-container
        image: serviceregistry:latest
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8761