spring.application.name=order-service

server.port=8092

spring.data.mongodb.uri=mongodb+srv://mahajit504_db_user:I0NlqbjPpnZ0itaB@cluster0.czzdasj.mongodb.net/orderdb?retryWrites=true&w=majority&appName=Cluster0

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=*
management.info.env.enabled=true